apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "asd"]
      restartPolicy: Never
