apiVersion: v1
kind: Pod
metadata:
    name: command-demo
    labels: 
        purpose: demo-command
spec:
  containers:
  - name: command-demo-container
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello world!!!!!!!!!; sleep 2;done"]
