apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
  labels:
    volume: ssd
  
spec:
  storageClassName: hostpath
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nfs/client"
