apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-pod
  name: redis-pod
spec:
  containers:
  - image: master:5000/redis
    name: redis-pod
  imagePullSecrets:
    - name: mydockercredentials
