apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-probe
  labels:
    app: goproxy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
       containers:
       - name: goproxy
         image: nginx
         ports:
         - containerPort: 80
         readinessProbe:
           tcpSocket:
             port: 8080
           initialDelaySeconds: 5
           periodSeconds: 10
         livenessProbe:
             tcpSocket:
               port: 8080
             initialDelaySeconds: 15
             periodSeconds: 20
